export const VERIFICATION = 'VERIFICATION';
export const VERIFICATION_FAILED = 'VERIFICATION FAILED';
export const SIGNATURE_VERIFICATION = 'SIGNATURE VERIFICATION'
export const RESET_STORE = "RESET_STORE";
